### ISSUE TITLE
Couldn't create xm32 directory

### ISSUE THREAD

**Issue by Dosh22** [davidgiga1993/mixing-station-docs#2]
Hi I have Mixing station Pro version in my Android phone Xiaomi Mi 9 Lite, but I still get error Couldn't create xm32 directory. Storage not ready. 

Android version 10.
I double checked the permission and storage access is allowed.

**Comment by davidgiga1993** [comment]
Hi,
This is not the bug tracker for mixing station. It can be found here: https://dev-core.org/mixing-station/help
The error "storage not ready" comes if android doesn't provide storage permissions to the app.
