### ISSUE TITLE
Incorrect screen orientationon Search activity 

### ISSUE THREAD

**Issue by da411d** [davidgiga1993/mixing-station-docs#5]
In settings I set force portrait orientation, and my phone is in vertical position, but when I press "search", screen rotates to landscape.

https://user-images.githubusercontent.com/12462454/140616919-3b3679db-ab38-4db7-9441-c107c1e08160.mp4

**Comment by davidgiga1993** [comment]
This repo is only for the documentation, app related issues can be reported here: 
https://mixingstation.app/help
