### ISSUE TITLE
Migrating Licenses

### ISSUE THREAD

**Issue by Stereobob** [davidgiga1993/mixing-station-docs#6]
I recently updated the APP, it worked fine on my newer tablet, my old tablet didn't, nor did my phone.  My old tablet is running Android 4.4.2, it will still run the old version of the App.  My Phone says it wants to migrate the license, I give it my Email and it says App already in use.   If I skip the migration it seems to work.  Why would it not migrate to that device, it did for the last 3 years.  Any help would be appreciated, thank you.

**Comment by davidgiga1993** [comment]
Note that this is the issue tracker for the documentation, not the app.
The migration guide can be found here:
https://mixingstation.app/ms-docs/platforms/android/#migration
