### ISSUE TITLE
Tap Tempo reacts to touch and release actions. It should only respond to touch actions.

### ISSUE THREAD

**Issue by duggyfresh** [davidgiga1993/mixing-station-docs#7]
To reproduce:
Create a tap tempo button.
Include BPM in the label.
Tap the button (releasing your finger as soon as possible) at 120 BPM. The rate is approximately correct at 120 BPM.
Now press the button at the same rate but release after half a second. The rate is set to 60 BPM.

It seems the tap and release actions are used to determine the rate.

**Comment by duggyfresh** [comment]
Sorry, can't reproduce this any more.

**Comment by davidgiga1993** [comment]
Keep in mind that this is only the documentation repo, the official bug reports are here: https://mixingstation.app/tasks/overview
You can report them here: https://mixingstation.app/help
